name: start_dart_workspace
description: START.DART V3 development workspace.
publish_to: none
version: 3.0.0

environment:
  sdk: ^3.11.0

workspace:
  - packages/start_dart
  - packages/start_dart_cli

dev_dependencies:
  very_good_analysis: ^10.3.0
