name: nativiq_workspace
description: Nativiq V3 development workspace.
publish_to: none
version: 3.0.0

environment:
  sdk: ^3.11.0

workspace:
  - packages/nativiq
  - packages/nativiq_cli

dev_dependencies:
  very_good_analysis: ^10.2.0
